name: C++ CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build the application
      run: g++ main.cpp -o HelloWorld

    - name: Build the tests
      run: g++ test.cpp -o tests

    - name: Run the application
      run: ./HelloWorld

    - name: Run the tests
      run: ./tests && echo "All tests passed!"

    - name: Zip the executable
      run: zip setup.zip HelloWorld

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: setup-zip
        path: ./setup.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only create a release on the main branch
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: setup-zip

    - name: Create GitHub Release
      id: create_release  # Capture the outputs for use in the next step
      uses: softprops/action-gh-release@v1  
      env:
        GITHUB_TOKEN: ${{ secrets.SUPERSECRET }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: "Release v1.0.${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  # Provide the upload_url from the previous step
        asset_path: ./setup.zip
        asset_name: setup.zip
        asset_content_type: application/zip
